"""
Source-to-Target Reconciliation Engine

Guarantees data completeness and integrity by mathematically balancing
source records against quarantined, standardized, and curated outputs.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple


class ReconciliationEngine:
    """Calculates and validates source-to-target count balancing."""

    def __init__(self, reports_dir: Path):
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def reconcile(
        self,
        run_id: str,
        source_name: str,
        source_count: int,
        quarantined_count: int,
        valid_count: int,
        duplicates_removed: int,
        curated_count: int,
    ) -> Dict[str, Any]:
        """
        Reconciles pipeline counts across all processing stages.
        Balance Equation:
            source_count == valid_count + quarantined_count
            curated_count == valid_count - duplicates_removed
        """
        expected_curated = valid_count - duplicates_removed
        source_balance = source_count - (valid_count + quarantined_count)
        curated_balance = curated_count - expected_curated

        is_source_balanced = (source_balance == 0)
        is_curated_balanced = (curated_balance == 0)
        overall_status = "PASS" if (is_source_balanced and is_curated_balanced) else "FAIL"

        report: Dict[str, Any] = {
            "run_id": run_id,
            "reconciled_at": datetime.now(timezone.utc).isoformat(),
            "source_name": source_name,
            "overall_status": overall_status,
            "counts": {
                "source_count": source_count,
                "quarantined_count": quarantined_count,
                "valid_count": valid_count,
                "duplicates_removed": duplicates_removed,
                "expected_curated": expected_curated,
                "curated_count": curated_count,
            },
            "variance": {
                "source_variance": source_balance,
                "curated_variance": curated_balance,
            },
            "balance_check": {
                "source_balanced": is_source_balanced,
                "curated_balanced": is_curated_balanced,
            },
            "formula": "source_count (100%) == valid_count + quarantined_count",
        }

        return report

    def save_reports(
        self,
        report: Dict[str, Any],
        run_id: str,
    ) -> Tuple[Path, Path]:
        """
        Persists both machine-readable JSON and human-readable Markdown reports.
        """
        json_path = self.reports_dir / f"reconciliation_{run_id}.json"
        md_path = self.reports_dir / f"reconciliation_{run_id}.md"

        # 1. Write JSON Report
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, default=str)

        # 2. Write Markdown Report
        counts = report["counts"]
        var = report["variance"]
        status_badge = "🟢 PASS" if report["overall_status"] == "PASS" else "🔴 FAIL"

        md_content = f"""# Source-to-Target Reconciliation Report

**Run ID:** `{run_id}`  
**Source Name:** `{report['source_name']}`  
**Reconciled At:** {report['reconciled_at']}  
**Overall Status:** {status_badge}  

---

## 1. Pipeline Count Balancing Ledger

| Processing Stage | Record Count | Explanation |
|---|:---:|---|
| **1. Source Ingested** | **{counts['source_count']}** | Total raw rows ingested from source file/API |
| **2. Quarantined (Rejected)** | **{counts['quarantined_count']}** | Non-compliant records diverted to quarantine |
| **3. Valid Passed Quality** | **{counts['valid_count']}** | Records passing all critical quality rules |
| **4. Duplicates Deduplicated** | **{counts['duplicates_removed']}** | Redundant duplicate primary keys removed |
| **5. Curated Published** | **{counts['curated_count']}** | Business-ready enriched analytical rows published |

---

## 2. Reconciliation Mathematical Verification

* **Stage 1 Balance Check:** `Source ({counts['source_count']}) == Valid ({counts['valid_count']}) + Quarantined ({counts['quarantined_count']})`  
  * **Discrepancy:** `{var['source_variance']}` $\\rightarrow$ **{'BALANCED' if report['balance_check']['source_balanced'] else 'UNBALANCED'}**
* **Stage 2 Balance Check:** `Curated ({counts['curated_count']}) == Valid ({counts['valid_count']}) - Duplicates ({counts['duplicates_removed']})`  
  * **Discrepancy:** `{var['curated_variance']}` $\\rightarrow$ **{'BALANCED' if report['balance_check']['curated_balanced'] else 'UNBALANCED'}**

---
*Generated by Case Management Enterprise Data Pipeline Reconciliation Engine.*
"""
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        return json_path, md_path
