"""
Unit Tests for Repository Layer

WHY REPOSITORY TESTS:
    Repository tests verify that data persistence, ORM mappings,
    foreign key constraints, audit trail insertion, and database queries
    execute correctly against an isolated SQLite test database.

NO MOCKS HERE:
    Unlike the service layer unit tests, repository tests DO NOT mock the database.
    They run against a real SQLite database session provided by the `db_session` fixture.
    This guarantees that the actual SQL statements generated by SQLAlchemy
    run without syntax errors or constraint violations.
"""

import pytest
from app.exceptions import CaseNotFoundError, UserNotFoundError
from app.models.case import Case, CaseHistory, CasePriority, CaseStatus, CaseType, User
from app.repositories.case_repository import CaseRepository, UserRepository


class TestCaseRepositoryUnit:
    """Test CaseRepository and UserRepository using real database sessions."""

    def test_user_repository_create_and_get(self, db_session):
        """Verify user creation and retrieval by ID."""
        repo = UserRepository()
        new_user = User(
            username="analyst1",
            email="analyst1@example.com",
            full_name="Analyst One",
            role="analyst",
        )

        created = repo.create(db_session, new_user)
        assert created.id is not None
        assert created.username == "analyst1"

        fetched = repo.get_by_id(db_session, created.id)
        assert fetched.id == created.id
        assert fetched.email == "analyst1@example.com"

    def test_user_repository_get_missing_raises_error(self, db_session):
        """Verify requesting a non-existent user raises UserNotFoundError."""
        repo = UserRepository()
        with pytest.raises(UserNotFoundError) as exc_info:
            repo.get_by_id(db_session, 99999)
        assert exc_info.value.user_id == 99999

    def test_case_create_persists_to_db(self, db_session, sample_user):
        """Verify that creating a case assigns an ID, timestamps, and persists properly."""
        repo = CaseRepository()
        case = Case(
            title="Payment Gateway Gateway Timeout",
            description="504 error during peak checkout hours",
            status=CaseStatus.OPEN,
            priority=CasePriority.CRITICAL,
            case_type=CaseType.BUG,
            created_by=sample_user.id,
        )

        persisted = repo.create(db_session, case)
        assert persisted.id is not None
        assert persisted.created_at is not None
        assert persisted.title == "Payment Gateway Gateway Timeout"
        assert persisted.status == CaseStatus.OPEN

    def test_case_get_by_id_success(self, db_session, sample_case):
        """Verify retrieving an existing case by its primary key ID."""
        repo = CaseRepository()
        fetched = repo.get_by_id(db_session, sample_case.id)
        assert fetched.id == sample_case.id
        assert fetched.title == sample_case.title

    def test_case_get_by_id_missing_raises_not_found(self, db_session):
        """Verify that querying a non-existent case ID raises CaseNotFoundError."""
        repo = CaseRepository()
        with pytest.raises(CaseNotFoundError) as exc_info:
            repo.get_by_id(db_session, 88888)
        assert exc_info.value.case_id == 88888

    def test_case_update_records_audit_history(self, db_session, sample_case, second_user):
        """
        Verify that updating a case updates the case record AND
        automatically records audit history entries in case_history table.
        """
        repo = CaseRepository()
        updates = {
            "status": CaseStatus.IN_PROGRESS,
            "priority": CasePriority.HIGH,
            "assigned_to": second_user.id,
        }

        updated = repo.update(db_session, sample_case, updates)
        assert updated.status == CaseStatus.IN_PROGRESS
        assert updated.priority == CasePriority.HIGH
        assert updated.assigned_to == second_user.id

        # Verify audit history records
        history_records = (
            db_session.query(CaseHistory)
            .filter(CaseHistory.case_id == sample_case.id)
            .order_by(CaseHistory.id)
            .all()
        )
        assert len(history_records) >= 2
        changed_fields = [h.field_changed for h in history_records]
        assert "status" in changed_fields
        assert "priority" in changed_fields

    def test_case_get_all_pagination_and_filtering(self, db_session, sample_user):
        """Verify get_all handles pagination limit/skip and status/priority filters."""
        repo = CaseRepository()
        for i in range(5):
            c = Case(
                title=f"Case Number {i}",
                status=CaseStatus.OPEN if i % 2 == 0 else CaseStatus.RESOLVED,
                priority=CasePriority.LOW,
                case_type=CaseType.INQUIRY,
                created_by=sample_user.id,
            )
            repo.create(db_session, c)

        cases, total = repo.get_all(db_session, skip=0, limit=2)
        assert len(cases) == 2
        assert total >= 5

        # Test filter by status
        open_cases, open_total = repo.get_all(db_session, status="OPEN")
        for oc in open_cases:
            assert oc.status == CaseStatus.OPEN
